# Related scripts
train_script_name: gan

# models' scripts
model_configs: 
  g_model:
    script: Conditional_Generator_Noskip
    class_name: Generator
    module_params:
      g_conv_dim: 32
      g_kernel_size: 3
      res_num: 8
      n_class: 11
  d_model:
    script: Conditional_Discriminator_Projection_big
    class_name: Discriminator
    module_params:
      d_conv_dim: 32
      d_kernel_size: 5

# Training information
total_epoch: 120
batch_size_list: [8, 4, 2] 
switch_epoch_list: [0, 5, 10]
imcrop_size_list: [256, 512, 768]
max2Keep: 10
movingAverage: 0.05
d_success_threshold: 0.8
d_step: 3
g_step: 1

# Dataset
dataloader: condition
dataset_name: styletransfer
dataset_params:
  random_seed: 1234
  dataloader_workers: 8
  color_jitter: Enable
  color_config:
    brightness: 0.05
    contrast:   0.05
    saturation: 0.05
    hue:        0.05
  selected_style_dir: ['berthe-morisot','edvard-munch',
                   'ernst-ludwig-kirchner','jackson-pollock','kandinsky','monet',
                   'nicholas','paul-cezanne','picasso','samuel','vangogh']
  selected_content_dir: ['a/abbey', 'a/arch', 'a/amphitheater', 'a/aqueduct', 'a/arena/rodeo', 'a/athletic_field/outdoor',
         'b/badlands', 'b/balcony/exterior', 'b/bamboo_forest', 'b/barn', 'b/barndoor', 'b/baseball_field',
         'b/basilica', 'b/bayou', 'b/beach', 'b/beach_house', 'b/beer_garden', 'b/boardwalk', 'b/boathouse',
         'b/botanical_garden', 'b/bullring', 'b/butte', 'c/cabin/outdoor', 'c/campsite', 'c/campus',
         'c/canal/natural', 'c/canal/urban', 'c/canyon', 'c/castle', 'c/church/outdoor', 'c/chalet',
         'c/cliff', 'c/coast', 'c/corn_field', 'c/corral', 'c/cottage', 'c/courtyard', 'c/crevasse',
         'd/dam', 'd/desert/vegetation', 'd/desert_road', 'd/doorway/outdoor', 'f/farm', 'f/fairway',
         'f/field/cultivated', 'f/field/wild', 'f/field_road', 'f/fishpond', 'f/florist_shop/indoor',
         'f/forest/broadleaf', 'f/forest_path', 'f/forest_road', 'f/formal_garden', 'g/gazebo/exterior',
         'g/glacier', 'g/golf_course', 'g/greenhouse/indoor', 'g/greenhouse/outdoor', 'g/grotto', 'g/gorge',
         'h/hayfield', 'h/herb_garden', 'h/hot_spring', 'h/house', 'h/hunting_lodge/outdoor', 'i/ice_floe',
         'i/ice_shelf', 'i/iceberg', 'i/inn/outdoor', 'i/islet', 'j/japanese_garden', 'k/kasbah',
         'k/kennel/outdoor', 'l/lagoon', 'l/lake/natural', 'l/lawn', 'l/library/outdoor', 'l/lighthouse',
         'm/mansion', 'm/marsh', 'm/mausoleum', 'm/moat/water', 'm/mosque/outdoor', 'm/mountain',
         'm/mountain_path', 'm/mountain_snowy', 'o/oast_house', 'o/ocean', 'o/orchard', 'p/park',
         'p/pasture', 'p/pavilion', 'p/picnic_area', 'p/pier', 'p/pond', 'r/raft', 'r/railroad_track',
         'r/rainforest', 'r/rice_paddy', 'r/river', 'r/rock_arch', 'r/roof_garden', 'r/rope_bridge',
         'r/ruin', 's/schoolhouse', 's/sky', 's/snowfield', 's/swamp', 's/swimming_hole',
         's/synagogue/outdoor', 't/temple/asia', 't/topiary_garden', 't/tree_farm', 't/tree_house',
         'u/underwater/ocean_deep', 'u/utility_room', 'v/valley', 'v/vegetable_garden', 'v/viaduct',
         'v/village', 'v/vineyard', 'v/volcano', 'w/waterfall', 'w/watering_hole', 'w/wave',
         'w/wheat_field', 'z/zen_garden', 'a/alcove', 'a/apartment-building/outdoor', 'a/artists_loft',
         'b/building_facade', 'c/cemetery']


eval_dataloader: DIV2K_hdf5
eval_dataset_name: DF2K_H5_Eval
eval_batch_size: 2

# Dataset

# Optimizer
optim_type: Adam
g_optim_config:
  lr: !!float 2e-4
  betas: [0.9, 0.99]
d_optim_config:
  lr: !!float 2e-4
  betas: [0.9, 0.99]

feature_weight: 50.0
transform_weight: 50.0
layers_weight: [1.0, 1.0, 1.0, 1.0, 1.0]

# Log 
log_step: 1000
sampleStep: 2000
model_save_epoch: 1
useTensorboard: True
checkpoint_names:
  generator_name: Generator
  discriminator_name: Discriminator